# Project information
site_name: 全志Linux Tina-SDK开发完全手册
site_url: https://github.com/DongshanPI/TinaSDK-Docs.git
site_author: 100askTeam
site_description: >-
  Tina SDK Docs Start Page.
copyright: Copyright &copy; 2008 - 2022 100ask Team
edit_uri: edit/master/docs/
repo_url: https://github.com/DongshanPI/TinaSDK-Docs/
repo_name: DongshanPI/TinaSDK-Docs

# Configuration
theme:
  name: material
  custom_dir: overrides
  # Static files
  static_templates:
    - 404.html
  # Don't include MkDocs' JavaScript
  include_search_page: true
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: zh
  features:
    - content.code.annotate
    # - content.tabs.link
    - header.autohide
    # - navigation.expand
    - navigation.indexes
    # - navigation.instant
    # - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    # - toc.follow
    # - toc.integrate
  palette:
    - scheme: default
      primary: teal
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: favicon.png
  icon:
    logo: dsp-logo

# Plugins
plugins:
  - search
  - markmap:
      base_path: docs
      encoding: utf-8
      file_extension: .mm.md
      d3_version: 6.7.0
      lib_version: 0.14.1
      view_version: 0.14.0 
#  - offline  
  - minify:
      minify_html: true
#  - social:
#      cards_color:
#        fill: "#0FF1CE" 
#        text: "#FFFFFF"
  - search:
      jieba_dict: dict.txt 
extra:
  analytics:
    provider: google
    property: G-LZX4K52CZ1
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >- # 
            Thanks for your feedback! Help us improve this page by
            using our <a href="..." target=_blank>feedback form</a>.      
  homepage: https://tina.100ask.net
  alternate:
    - name: English
      link: /en/
      lang: en
    - name: 中文
      link: /zh/
      lang: zh

      
#  disqus: dongshanpi-com

# Extensions
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - tables  
  - toc:
      slugify: !!python/name:pymdownx.slugs.uslugify  
  - toc:
      permalink: true
  - toc:
      title: On this page
  - toc:
      permalink_title: Anchor link to this section for reference
  - toc:
      toc_depth: 3      
  - pymdownx.arithmatex:
      generic: true        
  - pymdownx.arithmatex:
      generic: true

  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tilde  
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji 
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true   
  - pymdownx.snippets      
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - def_list      
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde

  
# Page tree
nav:
  - 0.站点指南:
    - 阅读指南: 'index.md'
    - 配套硬件: 'SupportHardware.md'
  - 1.构建工具使用:
    - TinaSDK_开发指南:
      - 概述与介绍: 'SdkModule/Linux_SystemSoftware_DevelopmentGuide-01.md'
      - Tina环境搭建: 'SdkModule/Linux_SystemSoftware_DevelopmentGuide-02.md'
      - Tina编译与烧写: 'SdkModule/Linux_SystemSoftware_DevelopmentGuide-03.md'
      - uboot与kernel定制开发: 'SdkModule/Linux_SystemSoftware_DevelopmentGuide-04.md'
      - 系统定制开发: 'SdkModule/Linux_SystemSoftware_DevelopmentGuide-05.md'
  - 2.Bootloader开发:
    - U-boot_开发指南:
      - 概述与介绍: 'SdkModule/Linux_U-boot_DevelopmentGuide-01.md'
      - 编译方法介绍: 'SdkModule/Linux_U-boot_DevelopmentGuide-02.md'
      - U-Boot功能与配置: 'SdkModule/Linux_U-boot_DevelopmentGuide-03.md'
      - U-Boot常用命令介绍: 'SdkModule/Linux_U-boot_DevelopmentGuide-04.md'
      - 调试方法与烧写: 'SdkModule/Linux_U-boot_DevelopmentGuide-05.md'
      - 常用接口函数: 'SdkModule/Linux_U-boot_DevelopmentGuide-06.md'
  - 3.Linux驱动开发:     
    - SID_开发指南:
      - 概述与介绍: 'SdkModule/Linux_SID_DevelopmentGuide-01.md'
      - 模块描述: 'SdkModule/Linux_SID_DevelopmentGuide-02.md'
      - 模块设计: 'SdkModule/Linux_SID_DevelopmentGuide-03.md'
      - 接口设计: 'SdkModule/Linux_SID_DevelopmentGuide-04.md'
      - 可测试性与其他说明: 'SdkModule/Linux_SID_DevelopmentGuide-05.md'
    - GPIO_开发指南:
      - 概述与介绍: 'SdkModule/Linux_GPIO_DevelopmentGuide-01.md'
      - 模块介绍: 'SdkModule/Linux_GPIO_DevelopmentGuide-02.md'
      - 模块配置: 'SdkModule/Linux_GPIO_DevelopmentGuide-03.md'
      - 模块接口说明: 'SdkModule/Linux_GPIO_DevelopmentGuide-04.md'
      - 使用示例: 'SdkModule/Linux_GPIO_DevelopmentGuide-05.md'
      - FAQ: 'SdkModule/Linux_GPIO_DevelopmentGuide-06.md'
    - MIPI_CSI_开发指南:
      - 概述与介绍: 'SdkModule/Linux_MIPI_CSI_DevelopmentGuide-01.md'
      - 模块介绍: 'SdkModule/Linux_MIPI_CSI_DevelopmentGuide-02.md'
      - V4L2接口描述: 'SdkModule/Linux_MIPI_CSI_DevelopmentGuide-03.md'
      - 模块使用范例: 'SdkModule/Linux_MIPI_CSI_DevelopmentGuide-04.md'
      - FAQ: 'SdkModule/Linux_MIPI_CSI_DevelopmentGuide-05.md'
    - MMC_开发指南:
      - 概述与介绍: 'SdkModule/Linux_MMC_DevelopmentGuide-01.md'
      - 模块介绍: 'SdkModule/Linux_MMC_DevelopmentGuide-02.md'
      - 模块接口说明: 'SdkModule/Linux_MMC_DevelopmentGuide-03.md'
      - FAQ: 'SdkModule/Linux_MMC_DevelopmentGuide-04.md'
    - RTC_开发指南:
      - 概述与介绍: 'SdkModule/Linux_RTC_DevelopmentGuide-01.md'
      - 模块介绍: 'SdkModule/Linux_RTC_DevelopmentGuide-02.md'
      - 模块配置介绍: 'SdkModule/Linux_RTC_DevelopmentGuide-03.md'
      - 接口描述: 'SdkModule/Linux_RTC_DevelopmentGuide-04.md'
      - 模块使用范例: 'SdkModule/Linux_RTC_DevelopmentGuide-05.md'
      - FAQ: 'SdkModule/Linux_RTC_DevelopmentGuide-06.md'
    - SPI_开发指南:
      - 概述与介绍: 'SdkModule/Linux_SPI_DevelopmentGuide-01.md'
      - 模块介绍: 'SdkModule/Linux_SPI_DevelopmentGuide-02.md'
      - 接口描述: 'SdkModule/Linux_SPI_DevelopmentGuide-03.md'
      - 模块使用范例: 'SdkModule/Linux_SPI_DevelopmentGuide-04.md'
      - FAQ: 'SdkModule/Linux_SPI_DevelopmentGuide-05.md'
    - Standby_开发指南:
      - 概述与介绍: 'SdkModule/Linux_Standby_DevelopmentGuide-01.md'
      - 模块介绍: 'SdkModule/Linux_Standby_DevelopmentGuide-02.md'
      - FAQ: 'SdkModule/Linux_Standby_DevelopmentGuide-03.md'
    - TWI_开发指南:
      - 概述与介绍: 'SdkModule/Linux_TWI_DevelopmentGuide-01.md'
      - 模块接口说明: 'SdkModule/Linux_TWI_DevelopmentGuide-02.md'
      - 模块使用范例: 'SdkModule/Linux_TWI_DevelopmentGuide-03.md'
      - FAQ: 'SdkModule/Linux_TWI_DevelopmentGuide-04.md'
    - UART_开发指南:
      - 概述与介绍: 'SdkModule/Linux_UART_DevelopmentGuide-01.md'
      - 模块配置介绍: 'SdkModule/Linux_UART_DevelopmentGuide-02.md'
      - 接口描述: 'SdkModule/Linux_UART_DevelopmentGuide-03.md'
      - 模块使用范例: 'SdkModule/Linux_UART_DevelopmentGuide-04.md'
      - FAQ: 'SdkModule/Linux_UART_DevelopmentGuide-05.md'
    - USB_开发指南:
      - 概述与介绍: 'SdkModule/Linux_USB_DevelopmentGuide-01.md'
      - 模块介绍: 'SdkModule/Linux_USB_DevelopmentGuide-02.md'
      - FAQ: 'SdkModule/Linux_USB_DevelopmentGuide-03.md'
      - 附录: 'SdkModule/Linux_USB_DevelopmentGuide-04.md'
    - Key_快速配置使用指南:
      - 概述与介绍: 'SdkModule/Linux_Key_Quick_Configuration_UserGuide-01.md'
      - 模块介绍: 'SdkModule/Linux_Key_Quick_Configuration_UserGuide-02.md'
      - GPIO-Key: 'SdkModule/Linux_Key_Quick_Configuration_UserGuide-03.md'
      - ADC-Key: 'SdkModule/Linux_Key_Quick_Configuration_UserGuide-04.md'
      - AXP-Key: 'SdkModule/Linux_Key_Quick_Configuration_UserGuide-05.md'
    - PMU_开发指南:
      - 概述与介绍: 'SdkModule/Linux_PMU_DevelopmentGuide-01.md'
      - 模块介绍: 'SdkModule/Linux_PMU_DevelopmentGuide-02.md'
      - 模块使用范例: 'SdkModule/Linux_PMU_DevelopmentGuide-03.md'
      - FAQ: 'SdkModule/Linux_PMU_DevelopmentGuide-04.md'
    - Wi-Fi_开发指南:
      - 概述与介绍: 'SdkModule/Linux_Wi-Fi_DevelopmentGuide-01.md'
      - Wi-Fi简介: 'SdkModule/Linux_Wi-Fi_DevelopmentGuide-02.md'
      - Wi-Fi模组移植: 'SdkModule/Linux_Wi-Fi_DevelopmentGuide-03.md'
      - Wi-Fi_manager与Softap介绍: 'SdkModule/Linux_Wi-Fi_DevelopmentGuide-04.md'
      - 常见问题: 'SdkModule/Linux_Wi-Fi_DevelopmentGuide-05.md'
  - 4.基础组件软件库:     
    - PWM_开发指南:
      - 概述与介绍: 'SdkModule/Linux_PWM_DevelopmentGuide-01.md' 
      - 模块描述:  'SdkModule/Linux_PWM_DevelopmentGuide-01.md' 
    - MPP_sample_使用说明:
      - 简述: 'SdkModule/Linux_MPP_Sample_Instructions-01.md' 
      - 配置编译测试: 'SdkModule/Linux_MPP_Sample_Instructions-02.md' 
      - 分类情况: 'SdkModule/Linux_MPP_Sample_Instructions-03.md' 
      - 各平台支持情况: 'SdkModule/Linux_MPP_Sample_Instructions-04.md' 
      - 测试方法: 'SdkModule/Linux_MPP_Sample_Instructions-05.md' 
      - FAQ: 'SdkModule/Linux_MPP_Sample_Instructions-06.md' 
    - Camera_开发指南:
      - 概述: 'SdkModule/Linux_Camera_DevelopmentGuide-01.md' 
      - 模块介绍: 'SdkModule/Linux_Camera_DevelopmentGuide-02.md' 
      - 模块开发: 'SdkModule/Linux_Camera_DevelopmentGuide-03.md' 
      - 模块配置: 'SdkModule/Linux_Camera_DevelopmentGuide-04.md' 
      - 模块调试常见问题: 'SdkModule/Linux_Camera_DevelopmentGuide-05.md' 
      - camera功能测试: 'SdkModule/Linux_Camera_DevelopmentGuide-06.md' 
    - E907_开发指南:
      - 概述与介绍: 'SdkModule/Linux_E907_DevelopmentGuide-01.md' 
      - 启动E907环境: 'SdkModule/Linux_E907_DevelopmentGuide-02.md' 
      - AMP环境搭建: 'SdkModule/Linux_E907_DevelopmentGuide-03.md' 
      - 开发使用: 'SdkModule/Linux_E907_DevelopmentGuide-04.md' 
      - 其他: 'SdkModule/Linux_E907_DevelopmentGuide-05.md' 
    - LCD_调试指南:
      - 概述与介绍: 'SdkModule/Linux_LCD_DevelopmentGuide-01.md' 
      - 模块介绍: 'SdkModule/Linux_LCD_DevelopmentGuide-02.md' 
      - 硬件参数说明:  'SdkModule/Linux_LCD_DevelopmentGuide-03.md' 
      - 调试方法: 'SdkModule/Linux_LCD_DevelopmentGuide-04.md' 
      - FAQ: 'SdkModule/Linux_LCD_DevelopmentGuide-05.md' 
      - 总结: 'SdkModule/Linux_LCD_DevelopmentGuide-06.md' 
    - Display_开发指南:
      - 概述与介绍: 'SdkModule/Linux_Display_DevelopmentGuide-01.md' 
      - 模块介绍: 'SdkModule/Linux_Display_DevelopmentGuide-02.md' 
      - 模块接口概述: 'SdkModule/Linux_Display_DevelopmentGuide-03.md' 
      - 操作与接口说明: 'SdkModule/Linux_Display_DevelopmentGuide-04.md' 
      - 输出设备介绍: 'SdkModule/Linux_Display_DevelopmentGuide-05.md' 
      - IOCTL接口描述: 'SdkModule/Linux_Display_DevelopmentGuide-06.md' 
      - sysfs接口描述: 'SdkModule/Linux_Display_DevelopmentGuide-07.md' 
      - 数据结构: 'SdkModule/Linux_Display_DevelopmentGuide-08.md' 
      - 调试: 'SdkModule/Linux_Display_DevelopmentGuide-09.md' 
    - 图形系统_开发指南:
      - 概述与介绍: 'SdkModule/Linux_GraphicsSystem_DevelopmentGuide-01.md' 
      - MiniGUI: 'SdkModule/Linux_GraphicsSystem_DevelopmentGuide-02.md' 
      - QT: 'SdkModule/Linux_GraphicsSystem_DevelopmentGuide-03.md' 
      - EFL与GTK+: 'SdkModule/Linux_GraphicsSystem_DevelopmentGuide-04.md' 
      - WebKitGtk与DirectFB: 'SdkModule/Linux_GraphicsSystem_DevelopmentGuide-05.md' 
      - Wayland: 'SdkModule/Linux_GraphicsSystem_DevelopmentGuide-06.md' 
      - LVGL: 'SdkModule/Linux_GraphicsSystem_DevelopmentGuide-07.md' 
      - Flutter: 'SdkModule/Linux_GraphicsSystem_DevelopmentGuide-08.md' 
    - 音频_开发指南:
      - 概述与介绍: 'SdkModule/Linux_AudioFrequency_DevelopmentGuide-01.md' 
      - 模块介绍: 'SdkModule/Linux_AudioFrequency_DevelopmentGuide-02.md' 
      - 常用工具及调试方法: 'SdkModule/Linux_AudioFrequency_DevelopmentGuide-03.md' 
      - 常用接口说明: 'SdkModule/Linux_AudioFrequency_DevelopmentGuide-04.md' 
      - 开机音乐功能: 'SdkModule/Linux_AudioFrequency_DevelopmentGuide-05.md' 
      - 各平台音频模块注意事项: 'SdkModule/Linux_AudioFrequency_DevelopmentGuide-06.md' 
    - WiFi_RF测试_使用指南:
      - 概述与介绍: 'SdkModule/Linux_WiFi_RFTest_UserGuide-01.md' 
      - WiFi测试: 'SdkModule/Linux_WiFi_RFTest_UserGuide-02.md' 
      - XRADIO系列模组: 'SdkModule/Linux_WiFi_RFTest_UserGuide-03.md' 
      - RTL系列模组: 'SdkModule/Linux_WiFi_RFTest_UserGuide-04.md' 
      - SRRC认证: 'SdkModule/Linux_WiFi_RFTest_UserGuide-05.md' 
    - 各平台多媒体格式支持列表:
      - 概述与介绍: 'SdkModule/Linux_Support_List_Multimedia_Formats_Each_Platform-01.md'
      - 芯片: 'SdkModule/Linux_Support_List_Multimedia_Formats_Each_Platform-02.md'
    - 配网_开发指南:
      - 概述与介绍: 'SdkModule/Linux_Distribution_Network_DevelopmentGuide-01.md'
      - wifimanager-v2.0配网: 'SdkModule/Linux_Distribution_Network_DevelopmentGuide-02.md'
      - 测试说明: 'SdkModule/Linux_Distribution_Network_DevelopmentGuide-03.md'
    - 网络性能_参考指南:
      - 概述与介绍: 'SdkModule/Linux_Network_Performance_Reference_Guide-01.md'
      - Wi-Fi性能测试: 'SdkModule/Linux_Network_Performance_Reference_Guide-02.md'
      - 蓝牙与WIFI蓝牙共存测试: 'SdkModule/Linux_Network_Performance_Reference_Guide-03.md'
  - 5.系统开发:      
    - 系统配置_开发指南:
      - 概述与配置介绍: 'SdkModule/Linux_Deploy_DevelopmentGuide-01.md'
      - 系统配置介绍: 'SdkModule/Linux_Deploy_DevelopmentGuide-02.md'
      - 设备树介绍: 'SdkModule/Linux_Deploy_DevelopmentGuide-03.md'
      - 设备树的使用与调试: 'SdkModule/Linux_Deploy_DevelopmentGuide-04.md'
      - 分区表说明: 'SdkModule/Linux_Deploy_DevelopmentGuide-05.md'
    - 系统调试_开发指南:
      - 概述与介绍: 'SdkModule/Linux_SystemDebug_DevelopmentGuide-01.md'
      - 调试方法及工具: 'SdkModule/Linux_SystemDebug_DevelopmentGuide-02.md'
    - 系统裁剪_参考指南:
      - 概述与介绍: 'SdkModule/Linux_SystemClipping_Reference_Guide-01.md'
      - 系统裁剪介绍: 'SdkModule/Linux_SystemClipping_Reference_Guide-02.md'
    - 启动优化_开发指南:
      - 概述与介绍: 'SdkModule/Linux_systemStartup_Optimization-01.md'  
      - 启动速度优化简介: 'SdkModule/Linux_systemStartup_Optimization-02.md'
      - Tina启动速度优化: 'SdkModule/Linux_systemStartup_Optimization-03.md'   
    - SPINAND_UBI_离线烧录_开发指南:
      - 概述与介绍: 'SdkModule/Linux_Spinubi_OfflineBurning_DevelopmentGuide-01.md'
      - 数据布局说明: 'SdkModule/Linux_Spinubi_OfflineBurning_DevelopmentGuide-02.md'
      - 调整内存说明: 'SdkModule/Linux_Spinubi_OfflineBurning_DevelopmentGuide-03.md'
    - NOR_开发指南:
      - 概述与介绍: 'SdkModule/Linux_NOR_DevelopmentGuide-01.md'
      - 模块介绍: 'SdkModule/Linux_NOR_DevelopmentGuide-02.md'
      - 接口描述: 'SdkModule/Linux_NOR_DevelopmentGuide-03.md'
      - 使用例子: 'SdkModule/Linux_NOR_DevelopmentGuide-04.md'
    - SPINAND 开发指南:
      - 概述与介绍: 'SdkModule/Linux_SPINAND_DevelopmentGuide-01.md'
      - 流程设计: 'SdkModule/Linux_SPINAND_DevelopmentGuide-02.md'
      - 模块配置: 'SdkModule/Linux_SPINAND_DevelopmentGuide-03.md'
    - 存储_开发指南:
      - 概述与介绍: 'SdkModule/Linux_Save_DevelopmentGuide-01.md'
      - 分区管理: 'SdkModule/Linux_Save_DevelopmentGuide-02.md'
      - 系统挂载: 'SdkModule/Linux_Save_DevelopmentGuide-03.md'
      - 文件系统支持情况: 'SdkModule/Linux_Save_DevelopmentGuide-04.md'
      - UBI_VS._NFTL: 'SdkModule/Linux_Save_DevelopmentGuide-05.md'
      - rootfs_data及UDISK: 'SdkModule/Linux_Save_DevelopmentGuide-06.md'
      - 关键数据保护: 'SdkModule/Linux_Save_DevelopmentGuide-07.md'
    - OTA_开发指南:
      - 概述与介绍: 'SdkModule/Linux_OTA_DevelopmentGuide-01.md'
      - ota-burnboot介绍: 'SdkModule/Linux_OTA_DevelopmentGuide-02.md'
      - Tina_SWUpdate_OTA介绍: 'SdkModule/Linux_OTA_DevelopmentGuide-03.md'
      - Tina_misc-upgrade介绍: 'SdkModule/Linux_OTA_DevelopmentGuide-04.md'
      - Tina_upgrade_app介绍: 'SdkModule/Linux_OTA_DevelopmentGuide-05.md'
      - 注意事项与问题排查: 'SdkModule/Linux_OTA_DevelopmentGuide-06.md'
    - syslog_使用指南:
      - 基本介绍: 'SdkModule/Linux_syslog_UserGuide-01.md'
      - syslog相关软件工具: 'SdkModule/Linux_syslog_UserGuide-02.md'
      - 不同syslog方案的对比: 'SdkModule/Linux_syslog_UserGuide-03.md'
      - 其他注意事项: 'SdkModule/Linux_syslog_UserGuide-04.md'
      - 在Tina中使用syslog: 'SdkModule/Linux_syslog_UserGuide-05.md'
    - 安全_开发指南:
      - 概述与介绍: 'SdkModule/Linux_Security_DevelopmentGuide-01.md'
      - 安全系统基础: 'SdkModule/Linux_Security_DevelopmentGuide-02.md'
      - 安全启动: 'SdkModule/Linux_Security_DevelopmentGuide-03.md'
      - 安全操作系统: 'SdkModule/Linux_Security_DevelopmentGuide-04.md'
      - TA/CA开发环境: 'SdkModule/Linux_Security_DevelopmentGuide-05.md'
      - 安全存储: 'SdkModule/Linux_Security_DevelopmentGuide-06.md'
      - 安全性增强的Linux: 'SdkModule/Linux_Security_DevelopmentGuide-07.md'
      - 量产工具: 'SdkModule/Linux_Security_DevelopmentGuide-08.md'
      - 参考资料: 'SdkModule/Linux_Security_DevelopmentGuide-09.md'
    - 功耗管理_开发指南:
      - 概述与介绍: 'SdkModule/Linux_Power_Consumption_Management_DevelopmentGuide-01.md'
      - Tina功耗管理框架概述: 'SdkModule/Linux_Power_Consumption_Management_DevelopmentGuide-02.md'
      - Tina休眠唤醒系统简介: 'SdkModule/Linux_Power_Consumption_Management_DevelopmentGuide-03.md'
      - 差异化方案说明: 'SdkModule/Linux_Power_Consumption_Management_DevelopmentGuide-04.md'
      - FAQ问题及处理方法: 'SdkModule/Linux_Power_Consumption_Management_DevelopmentGuide-05.md'
    - 内存优化_开发指南:
      - 概述与介绍: 'SdkModule/Linux_Memory_Optimization_DevelopmentGuide-01.md'
      - 内存使用情况分析: 'SdkModule/Linux_Memory_Optimization_DevelopmentGuide-02.md'
      - 内存优化: 'SdkModule/Linux_Memory_Optimization_DevelopmentGuide-03.md'
    - 存储性能_参考指南:
      - 概述与介绍: 'SdkModule/Linux_Storage_Performance_Reference_Guide-01.md'
      - 经验性能值: 'SdkModule/Linux_Storage_Performance_Reference_Guide-02.md'
      - 顺序与随机读写性能: 'SdkModule/Linux_Storage_Performance_Reference_Guide-03.md'
      - 读写性能的影响因素: 'SdkModule/Linux_Storage_Performance_Reference_Guide-04.md'
    - 打包流程_说明指南:
      - 概述与介绍: 'SdkModule/Linux_Packaging_Process_DescriptionGuide-01.md'
      - 打包工具介绍: 'SdkModule/Linux_Packaging_Process_DescriptionGuide-02.md'
      - 打包脚本分析: 'SdkModule/Linux_Packaging_Process_DescriptionGuide-03.md'
      - 获得打包后的分区镜像文件: 'SdkModule/Linux_Packaging_Process_DescriptionGuide-04.md'
      - 打包常见问题FAQ: 'SdkModule/Linux_Packaging_Process_DescriptionGuide-05.md'
      - 打包流程总结: 'SdkModule/Linux_Packaging_Process_DescriptionGuide-06.md'
    - 量产测试_使用指南:
      - 概述与介绍: 'SdkModule/Linux_Mass_Production_UserGuide-01.md'
      - 配置: 'SdkModule/Linux_Mass_Production_UserGuide-02.md'
      - 测试环境搭建: 'SdkModule/Linux_Mass_Production_UserGuide-03.md'
      - 量产测试流程: 'SdkModule/Linux_Mass_Production_UserGuide-04.md'
      - 各平台Tinatest场景验证表: 'SdkModule/Linux_Mass_Production_UserGuide-05.md'
  - 6.应用示例与项目:
    - UART_开发指南:
      - 概述与介绍: 'SdkModule/Linux_UART_DevelopmentGuide-01.md'          
extra_javascript:
  - javascripts/shortcuts.js

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - https://unpkg.com/d3@6.7.0/dist/d3.min.js
  - https://unpkg.com/markmap-lib@0.14.1/dist/browser/index.min.js
  - https://unpkg.com/markmap-view@0.14.0/dist/index.min.js
