# Project information
site_name: Tina SDK Documentation Center.
site_url: https://github.com/DongshanPI/TinaSDK-Docs.git
site_author: 100askTeam
site_description: >-
  Tina SDK Docs Start Page.
copyright: Copyright &copy; 2008 - 2022 100ask Team
edit_uri: edit/master/docs/
repo_url: https://github.com/DongshanPI/TinaSDK-Docs/
repo_name: DongshanPI/TinaSDK-Docs

# Configuration
theme:
  name: material
  custom_dir: overrides
  # Static files
  static_templates:
    - 404.html
  # Don't include MkDocs' JavaScript
  include_search_page: true
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: zh
  features:
    - content.code.annotate
    # - content.tabs.link
    - header.autohide
    # - navigation.expand
    - navigation.indexes
    # - navigation.instant
    # - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    # - toc.follow
    # - toc.integrate
  palette:
    - scheme: default
      primary: teal
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: favicon.png
  icon:
    logo: dsp-logo

# Plugins
plugins:
  - search
  - markmap:
      base_path: docs
      encoding: utf-8
      file_extension: .mm.md
      d3_version: 6.7.0
      lib_version: 0.14.1
      view_version: 0.14.0 
#  - offline  
  - minify:
      minify_html: true
#  - social:
#      cards_color:
#        fill: "#0FF1CE" 
#        text: "#FFFFFF"
  - search:
      jieba_dict: dict.txt 
extra:
  analytics:
    provider: google
    property: G-LZX4K52CZ1
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >- # 
            Thanks for your feedback! Help us improve this page by
            using our <a href="..." target=_blank>feedback form</a>.      
  homepage: https://tina.100ask.net
  alternate:
    - name: English
      link: /en/
      lang: en
    - name: 中文
      link: /zh/
      lang: zh

      
#  disqus: dongshanpi-com

# Extensions
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - tables  
  - toc:
      slugify: !!python/name:pymdownx.slugs.uslugify  
  - toc:
      permalink: true
  - toc:
      title: On this page
  - toc:
      permalink_title: Anchor link to this section for reference
  - toc:
      toc_depth: 3      
  - pymdownx.arithmatex:
      generic: true        
  - pymdownx.arithmatex:
      generic: true

  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tilde  
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji 
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true   
  - pymdownx.snippets      
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - def_list      
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde

  
# Page tree
nav:
  - 网站简述:
    - 网站简介: 'index.md'
    - LinuxSDK模块开发指南: 'SdkModuleDevelopment.md'
    - Linux基础组件开发指南: 'BasicComponentDevelopment.md'
  - Linux-SDK模块开发指南上:     
    - UART_开发指南:
      - 概述与介绍: 'SdkModule/Linux_UART_DevelopmentGuide-01.md'
      - 模块配置介绍: 'SdkModule/Linux_UART_DevelopmentGuide-02.md'
      - 接口描述: 'SdkModule/Linux_UART_DevelopmentGuide-03.md'      
      - 模块使用范例: 'SdkModule/Linux_UART_DevelopmentGuide-04.md'            
      - 常见问题: 'SdkModule/Linux_UART_DevelopmentGuide-05.md'                  
    - GPIO_开发指南:
      - 概述与介绍: 'SdkModule/Linux_GPIO_DevelopmentGuide-01.md'
      - 模块配置介绍: 'SdkModule/Linux_GPIO_DevelopmentGuide-02.md'
      - 接口描述: 'SdkModule/Linux_GPIO_DevelopmentGuide-03.md'      
      - 模块使用范例: 'SdkModule/Linux_GPIO_DevelopmentGuide-04.md'            
      - 常见问题: 'SdkModule/Linux_GPIO_DevelopmentGuide-05.md'          
    - LCD_开发指南: 
      - 概述与介绍: 'SdkModule/Linux_LCD_DevelopmentGuide-01.md'
      - IC规格: 'SdkModule/Linux_LCD_DevelopmentGuide-02.md'
      - 模块介绍: 'SdkModule/Linux_LCD_DevelopmentGuide-03.md'      
      - 硬件参数说明: 'SdkModule/Linux_LCD_DevelopmentGuide-04.md'        
    - TWI_开发指南: 
      - 概述与介绍: 'SdkModule/Linux_TWI_DevelopmentGuide-01.md'
      - 模块接口说明: 'SdkModule/Linux_TWI_DevelopmentGuide-02.md'
      - 模块使用范例: 'SdkModule/Linux_TWI_DevelopmentGuide-03.md'            
      - 常见问题: 'SdkModule/Linux_TWI_DevelopmentGuide-04.md' 
    - CCU_开发指南:
      - 概述: 'SdkModule/Linux_CCU_DevelopmentGuide-01.md'
      - 模块介绍: 'SdkModule/Linux_CCU_DevelopmentGuide-02.md'      
      - 模块接口说明: 'SdkModule/Linux_CCU_DevelopmentGuide-03.md'            
      - 模块使用规范: 'SdkModule/Linux_CCU_DevelopmentGuide-04.md'                  
    - CE开发指南: 'SdkModule/Linux_CE_DevelopmentGuide-01.md' 
    - DMAC_开发指南: 'SdkModule/Linux_DMAC_DevelopmentGuide-01.md'
    - G2D_开发指南: 'SdkModule/Linux_G2D_DevelopmentGuide-01.md'
    - CE开发指南: 'SdkModule/Linux_CE_DevelopmentGuide-01.md'
    - DMAC_开发指南: 'SdkModule/Linux_EMAC_DevelopmentGuide-01.md'
    - Display_开发指南: 'SdkModule/Linux_Display_DevelopmentGuide-01.md'
    - EMAC_开发指南: 'SdkModule/Linux_EMAC_DevelopmentGuide-01.md'
    - GPADC_开发指南: 'SdkModule/Linux_GPADC_DevelopmentGuide-01.md'
    - ISP_开发指南: 'SdkModule/Linux_ISP_DevelopmentGuide-01.md'
  - Linux-SDK模块开发指南下:    
    - MIPI_CSI_开发指南: 'SdkModule/Linux_MIPI_CSI_DevelopmentGuide-01.md'
    - MMC_开发指南: 'SdkModule/Linux_MMC_DevelopmentGuide-01.md'
    - Nor_开发指南: 'SdkModule/Linux_Nor_DevelopmentGuide-01.md'
    - PMIC_开发指南: 'SdkModule/Linux_PMIC_DevelopmentGuide-01.md'
    - RTC_开发指南: 'SdkModule/Linux_RTC_DevelopmentGuide-01.md'
    - SID_开发指南: 'SdkModule/Linux_SID_DevelopmentGuide-01.md'
    - SPI-NAND_开发指南: 'SdkModule/Linux_SPI-NAND_DevelopmentGuide-01.md'
    - SPINAND_UBI离线烧录_开发指南: 'SdkModule/Linux_SPINAND_UBIOfflineProgramming_DevelopmentGuide-01.md'
    - SPI_开发指南: 'SdkModule/Linux_SPI_DevelopmentGuide-01.md'
    - Standby_开发指南: 'SdkModule/Linux_Standby_DevelopmentGuide-01.md'
    - U-Boot_开发指南: 'SdkModule/Linux_U-Boot_DevelopmentGuide-01.md'
    - USB_开发指南: 'SdkModule/Linux_USB_DevelopmentGuide-01.md'
    - 安全_开发指南: 'SdkModule/Linux_Security_DevelopmentGuide-01.md'    
  - Linux基础组件开发指南上:
    - Linux_PWM_开发指南:
      - 概述: 'BasicComponent/Linux_PWM_DevelopmentGuide-01.md'
      - 术语及概念: 'BasicComponent/Linux_PWM_DevelopmentGuide-02.md'   
      - 模块描述: 'BasicComponent/Linux_PWM_DevelopmentGuide-03.md'          
    - MPP_Sample_使用说明: 'BasicComponent/MPP_Sample_Instructionsforuse-01.md'
    - E907开发指南:
      - 简述: 'BasicComponent/Linux_E907_DevelopmentGuide-01.md'
      - 环境搭建: 'BasicComponent/Linux_E907_DevelopmentGuide-02.md'      
      - 开发使用: 'BasicComponent/Linux_E907_DevelopmentGuide-03.md'
      - 常见问题: 'BasicComponent/Linux_E907_DevelopmentGuide-04.md'
    - LCD_调试指南:
      - 简述: 'BasicComponent/Linux_LCD_DebuggingGuide-01.md'
      - 模块介绍: 'BasicComponent/Linux_LCD_DebuggingGuide-02.md'
      - 硬件参数说明: 'BasicComponent/Linux_LCD_DebuggingGuide-03.md'       
      - 调试方法: 'BasicComponent/Linux_LCD_DebuggingGuide-04.md'
      - 常见问题: 'BasicComponent/Linux_LCD_DebuggingGuide-05.md'
    - Display_开发指南:
      - 简述: 'BasicComponent/Linux_Display_DevelopmentGuide-01.md'
      - 模块接口概述: 'BasicComponent/Linux_Display_DevelopmentGuide-02.md'
      - 显示接口参数说明: 'BasicComponent/Linux_Display_DevelopmentGuide-03.md'
      - 输出设备介绍: 'BasicComponent/Linux_Display_DevelopmentGuide-04.md'
      - IOCTL接口描述: 'BasicComponent/Linux_Display_DevelopmentGuide-05.md'            
      - sysfs接口描述: 'BasicComponent/Linux_Display_DevelopmentGuide-06.md'                  
      - Data Structure: 'BasicComponent/Linux_Display_DevelopmentGuide-07.md'                        
      - 调试: 'BasicComponent/Linux_Display_DevelopmentGuide-08.md'                              
    - Camera_开发指南: 'BasicComponent/Linux_Camera_DevelopmentGuide-01.md'
    - Key_快速配置_使用指南: 'BasicComponent/Linux_Key_QuickConfiguration_UserGuide-01.md'
    - OTA_开发指南: 'BasicComponent/Linux_OTA_DevelopmentGuide-01.md'
    - PMU_开发指南: 'BasicComponent/Linux_PMU_DevelopmentGuide-01.md'
    - USB_开发指南: 'BasicComponent/Linux_USB_DevelopmentGuide-01.md'    
  - Linux基础组件开发指南中: 
    - 网络性能_参考指南: 'BasicComponent/Linux_NetworkPerformance_ReferenceGuide-01.md'
    - 蓝牙_开发指南: 'BasicComponent/Linux_Bluetooth_DevelopmentGuide-01.md'
    - 蓝牙_模组移植指南: 'BasicComponent/Linux_Bluetooth_ModuleMigrationGuide-01.md'
    - Wi-Fi_开发指南: 'BasicComponent/Linux_Wi-Fi_DevelopmentGuide-01.md'
    - WiFi_RF测试_使用指南: 'BasicComponent/Linux_WiFi_RFTest_UsageGuide-01.md'    
    - 配网_开发指南: 'BasicComponent/Linux_DistributionNetwork_DevelopmentGuide-01.md'
    - 配置_开发指南: 'BasicComponent/Linux_Configuration_DevelopmentGuide-01.md'
    - 音频_开发指南: 'BasicComponent/Linux_Audio_DevelopmentGuide-01.md'
    - NPU开发简介: 'BasicComponent/IntroductiontoLinux_NPUDevelopment-01.md'
    - NPU混合量化部署: 'BasicComponent/Linux_NPUmixedquantitativedeployment-01.md'
    - NPU部署工具安装指导: 'BasicComponent/Linux_NPUdeploymenttoolinstallationguide-01.md'    
    - NPU_AI模型混合量化指导: 'BasicComponent/Linux_NPU_AIModelHybridQuantizationGuide-01.md'
    - NPU_Lenet模型之从训练到端侧部署: 'BasicComponent/Linux_NPU_Lenetmodelfromtrainingtoend-sidedeployment-01.md'
    - NPU_VIPLite_API说明: 'BasicComponent/DescriptionofLinux_NPU_VIPLite_API-01.md'
    - NPU_Yolact模型部署: 'BasicComponent/Linux_NPU_Yolactmodeldeployment-01.md'
    - NPU常见网络性能分析数据: 'BasicComponent/Linux_NPUcommonnetworkperformanceanalysisdata-01.md'
  - Linux基础组件开发指南下:    
    - syslog_使用指南: 'BasicComponent/Linux_syslog_UsageGuide-01.md'
    - 内存优化_开发指南: 'BasicComponent/Linux_MemoryOptimization_DevelopmentGuide-01.md'
    - 功耗管理_开发指南: 'BasicComponent/Linux_PowerManagement_DevelopmentGuide-01.md'
    - 各平台多媒体格式: 'BasicComponent/Linux_Multimediaformatsforeachplatform-01.md'
    - 启动优化_开发指南: 'BasicComponent/Linux_BootOptimization_DevelopmentGuide-01.md'
    - 图形系统_开发指南: 'BasicComponent/Linux_GraphicsSystem_DevelopmentGuide-01.md'
    - 多媒体MPP_开发指南: 'BasicComponent/Linux_MultimediaMPP_DevelopmentGuide-01.md'
    - 存储_开发指南: 'BasicComponent/Linux_Storage_DevelopmentGuide-01.md'
    - 存储性能_参考指南: 'BasicComponent/Linux_StoragePerformance_ReferenceGuide-01.md'
    - 安全_开发指南: 'BasicComponent/Linux_Security_DevelopmentGuide-01.md'
    - 打包流程_说明指南: 'BasicComponent/Linux_packagingprocess_instructionguide-01.md'
    - 系统裁剪_开发指南: 'BasicComponent/Linux_SystemTailoring_DevelopmentGuide-01.md'
    - 系统调试_使用指南: 'BasicComponent/Linux_SystemDebugging_UsageGuide-01.md'
    - 系统软件_开发指南: 'BasicComponent/Linux_SystemSoftware_DevelopmentGuide-01.md'

extra_javascript:
  - javascripts/shortcuts.js

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - https://unpkg.com/d3@6.7.0/dist/d3.min.js
  - https://unpkg.com/markmap-lib@0.14.1/dist/browser/index.min.js
  - https://unpkg.com/markmap-view@0.14.0/dist/index.min.js  

