name: Bug Report
description: Report a bug
body:
  - type: checkboxes
    attributes:
      label: Contribution guidelines
      description: Please read the contribution guidelines before proceeding.
      options:
        - label: I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree
          required: true
  - type: checkboxes
    attributes:
      label: I've found a bug and checked that ...
      description: Make sure that your request fulfills all of the following requirements. If one requirement cannot be satisfied, explain in detail why.
      options:
      - label: ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
        required: true
      - label: ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
      - label: ... the documentation does not mention anything about my problem
      - label: ... there are no open or closed issues that are related to my problem
  - type: textarea
    attributes:
      label: Description
      description: Please provide a brief description of the bug in 1-2 sentences.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behaviour
      description: Please describe precisely what you'd expect to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Actual behaviour
      description: Please describe precisely what is actually happening.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: Please describe the steps to reproduce the bug.
      placeholder: |-
        1. ...
        2. ...
        3. ...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Package versions
      description: Please provide all package versions, i.e. run the commands in backticks on a shell.
      value: |-
        - Python: `python --version`
        - MkDocs: `mkdocs --version`
        - Material: `pip show mkdocs-material | grep -E ^Version`
    validations:
      required: true
  - type: textarea
    attributes:
      label: Configuration
      description: Please provide a minimal (!) `mkdocs.yml` to reproduce the bug.
      placeholder: |-
        site_name: My Docs
        site_url: https://example.com/docs
      render: yaml
    validations:
      required: true
  - type: textarea
    attributes:
      label: System information
      description: Please provide your operating system and browser type and version.
      value: |-
        - Operating system: ...
        - Browser: ...
    validations:
      required: true
